In [86]:
# import numpy as np
# import pandas as pd 
# data = pd.read_csv('spam.csv', encoding='ISO-8859-1')

# # data = np.genfromtxt('emails.csv', delimiter=',', skip_header=1)
# data.shape
# df = pd.read_csv("spam.csv",nrows=5000, encoding='ISO-8859-1')
# # print(df)
# df


In [87]:
# df = df.drop(columns=df.columns[df.columns.str.contains('Unnamed')])

# df[:5]

In [88]:
import keras
import numpy as np
import pandas as pd
import tensorflow
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from numpy import nan
import nltk
import sklearn.feature_extraction.text as pre
from sklearn import preprocessing
from sklearn.feature_extraction.text import CountVectorizer
import pickle as pk

In [89]:
data=pd.read_csv("spamPretraité.csv")
Y = data["label"].to_numpy() 
Y[Y == "ham"]=0
Y[Y == "spam"]=1
Y = Y.astype('int')

In [90]:
Y

array([0, 0, 1, ..., 0, 1, 1])

In [91]:
X=pd.read_csv("countMatrix")
X= X.to_numpy()

In [92]:
 

 
X_train = X[0:3300]
X_test = X[3300:4197]
Y_train = Y[0:3300]
Y_test = Y[3300:4197]
from sklearn.preprocessing import MinMaxScaler
# Normalize data


# print(X_train)

print(Y_train.shape)
print(Y_test.shape)

(3300,)
(897,)


In [93]:
X_train = np.asarray(X_train).astype('float32')
# X_train = tensorflow.expand_dims(X_train, axis=-1)
# X_train = tensorflow.expand_dims(X_train, axis=-1)


# Y_train = np.asarray(Y_train).astype('float32')
# X_test = np.asarray(X_test).astype('float32')
# X_test = tensorflow.expand_dims(X_test, axis=-1)
# X_test = tensorflow.expand_dims(X_test, axis=-1)
# Y_test = np.asarray(Y_test).astype('float32')
# print(X_train.shape)
# print(X_test.shape)
X_train.shape

(3300, 12905)

In [94]:
# data =data.drop(columns=data.columns[data.columns.str.contains('Unnamed')])
# data.columns

In [95]:
# data['Spam']=data['v1'].apply(lambda x:1 if x=='spam' else 0)
# data.head(5)

In [96]:
# from sklearn.model_selection import train_test_split
# X_train,X_test,y_train,y_test=train_test_split(data.v2,data.Spam,test_size=0.25)


In [97]:
from sklearn.feature_extraction.text import CountVectorizer 

**Naive Bayes Have three Classifier(Bernouli,Multinominal,Gaussian)
Here I use Multinominal Bayes Because here data in a discrete form 
discrete data(e.g movie ratings ranging  1 to 5 as each rating will have certain frequency to represent)**

In [98]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier



In [99]:
# from sklearn.pipeline import Pipeline
# clf=Pipeline([
#     ('vectorizer' , CountVectorizer()) ,
#     ('nb' ,MultinomialNB())
# ])

In [100]:
print(X_train)

[[0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [3.297e+03 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [3.298e+03 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [3.299e+03 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]]


In [101]:
model =RandomForestClassifier()

In [102]:
model.fit(X_train ,Y_train)

RandomForestClassifier()

In [103]:
emails=[
    'Sounds great! Are you home now?',
    'Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES'
]

Preprocessing :


In [108]:
import preprocessing
preprocessing.preprocess_email(emails)

[' sound great are you home now',
 ' will u meet ur dream partner soon is ur career off nombr a flyng start nombr find out free txt horo follow by ur star sign e g horo ari']

In [109]:
model.predict(emails)

ValueError: could not convert string to float: 'Sounds great! Are you home now?'

In [107]:
model.score(X_test ,Y_test)

0.9754738015607581